# Generated by Django 3.2.6 on 2021-09-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.FileField(null=True, upload_to='static/uploads'),
        ),
    ]
