# Generated by Django 3.2.6 on 2021-09-21 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_news_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('New_cases', models.IntegerField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('Total_deaths', models.IntegerField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('Total_recovered', models.IntegerField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_title',
            field=models.CharField(max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
