# Generated by Django 3.2.6 on 2021-09-22 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20210922_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='New_cases',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='covid',
            name='Total_deaths',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='covid',
            name='Total_recovered',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
