# Generated by Django 3.2.6 on 2021-09-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news_title',
            new_name='new_cases',
        ),
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_image',
        ),
        migrations.AddField(
            model_name='news',
            name='recovered_patients',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='recovery_percentage',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='tests_done',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='total_deaths',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
