# Generated by Django 3.2.6 on 2021-09-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='Contact_Number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='firstname',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='lastname',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
